services:
  db:
    image: postgres:15
    container_name: todo_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password123}
      - POSTGRES_DB=todo_database
    ports:
      - "5433:5432" 
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db